### ISSUE TITLE
Transfer Stake

### ISSUE THREAD

**Issue by dziedom** [Zilliqa/Zillion-issue#29] opened 2020-09-22 15:29 UTC
When i try to transfer stake from Pickachu  to sentinal it throws an error saying it needs to be a bech32 address

**Comment by dziedom** [comment] 2020-09-22 15:31
When i try to transfer stake from Pickachu to sentinal it throws an error saying it needs to be a bech32 address
![bech32](https://user-images.githubusercontent.com/62773889/93903747-fc17f300-fcf0-11ea-9bbd-d3d448dadbbd.png)

**Comment by AmritKumar** [comment] 2020-09-23 21:12
We are not able to reproduce this. Is there any more info you could provide? Thanks!

**Comment by AmritKumar** [comment] 2020-09-24 11:37
It should be fixed now. Thanks for reporting it. I am closing it for now.

**Closed as completed by AmritKumar** 2020-09-24 11:37 UTC
Labels: ui-issue
