### ISSUE TITLE
Error while re-delegation ( bech32 or checksum address error)

### ISSUE THREAD

**Issue by devranjan** [Zilliqa/Zillion-issue#32] opened 2020-09-22 20:19 UTC
Sometimes it gives an error " operator address should be bech32 or checksum format". Again after selecting the same or other delegation address, the stacking works.
![delegation error 32](https://user-images.githubusercontent.com/11460583/93936459-d962fa00-fd43-11ea-8125-3c9437c7c1a0.gif)

**Comment by AmritKumar** [comment] 2020-09-23 21:10
We are not able to reproduce this. Is there any more info you could provide that could reproduce this?

**Comment by devranjan** [comment] 2020-09-23 22:59
> We are not able to reproduce this. Is there any more info you could provide that could reproduce this?

While re-deligation (re-stacking), sometimes it gives an error stating "operator address should be bech32 or checksum format". You can see in the above screenshot gif. But after trying some more time, it get re-stacked. 
**So, my point is it gives error sometimes while re-staking the token.**

I have only 195 test ZIL remaining and I even can't withdraw the stack. If you could send me some, I can try it again. Or even your team can test it.

**Comment by AmritKumar** [comment] 2020-09-24 11:36
This should be fixed now. Thanks for reporting this. I am closing this for now.

**Closed as completed by AmritKumar** 2020-09-24 11:36 UTC
Labels: ui-issue
